# Generated by Django 5.2.6 on 2025-11-01 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'ก่อนทำงาน'), ('AFTER', 'หลังทำงาน')], max_length=10)),
                ('image', models.ImageField(upload_to='before_after/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_photos', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'before_after_photos',
                'ordering': ['photo_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1 ดาว'), (2, '2 ดาว'), (3, '3 ดาว'), (4, '4 ดาว'), (5, '5 ดาว')])),
                ('response_speed_rating', models.IntegerField(blank=True, choices=[(1, '1 ดาว'), (2, '2 ดาว'), (3, '3 ดาว'), (4, '4 ดาว'), (5, '5 ดาว')], null=True)),
                ('work_quality_rating', models.IntegerField(blank=True, choices=[(1, '1 ดาว'), (2, '2 ดาว'), (3, '3 ดาว'), (4, '4 ดาว'), (5, '5 ดาว')], null=True)),
                ('politeness_rating', models.IntegerField(blank=True, choices=[(1, '1 ดาว'), (2, '2 ดาว'), (3, '3 ดาว'), (4, '4 ดาว'), (5, '5 ดาว')], null=True)),
                ('cleanliness_rating', models.IntegerField(blank=True, choices=[(1, '1 ดาว'), (2, '2 ดาว'), (3, '3 ดาว'), (4, '4 ดาว'), (5, '5 ดาว')], null=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
